export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: { sans: ['"Poppins"', "system-ui", "sans-serif"] },
      borderRadius: { sm: "8px", md: "12px", lg: "16px", pill: "9999px" },
      boxShadow: {
        sm: "0 1px 2px rgba(13,18,15,0.06)",
        md: "0 4px 12px rgba(13,18,15,0.08)",
        lg: "0 12px 32px rgba(13,18,15,0.12)",
      },
      backgroundColor: {
        canvas: "var(--color-bg-canvas)",
        surface: "var(--color-bg-surface)",
        subtle: "var(--color-bg-subtle)",
        strong: "var(--color-bg-strong)",
        brand: "var(--color-bg-brand)",
        "brand-hover": "var(--color-bg-brand-hover)",
        "brand-subtle": "var(--color-bg-brand-subtle)",
        disabled: "var(--color-bg-disabled)",
        success: "var(--color-bg-success)",
        warning: "var(--color-bg-warning)",
        danger: "var(--color-bg-danger)",
        info: "var(--color-bg-info)",
      },
      textColor: {
        primary: "var(--color-text-primary)",
        secondary: "var(--color-text-secondary)",
        muted: "var(--color-text-muted)",
        disabled: "var(--color-text-disabled)",
        brand: "var(--color-text-brand)",
        "on-brand": "var(--color-text-on-brand)",
        inverse: "var(--color-text-inverse)",
        success: "var(--color-text-success)",
        warning: "var(--color-text-warning)",
        danger: "var(--color-text-danger)",
        info: "var(--color-text-info)",
      },
      borderColor: {
        DEFAULT: "var(--color-border-default)",
        subtle: "var(--color-border-subtle)",
        strong: "var(--color-border-strong)",
        brand: "var(--color-border-brand)",
        focus: "var(--color-border-focus)",
        disabled: "var(--color-border-disabled)",
        success: "var(--color-border-success)",
        warning: "var(--color-border-warning)",
        danger: "var(--color-border-danger)",
        info: "var(--color-border-info)",
      },
    },
  },
  plugins: [],
};
